#!/usr/bin/env python3
"""Build a deterministic authority.json from an operator-owned descriptor.

This unprivileged helper computes file and descriptor pins. Installation and
enrollment remain authenticated root operations; its output is never authority
merely because it was generated by this repository.
"""
import argparse,hashlib,json,os
from pathlib import Path

def canonical(v):return json.dumps(v,sort_keys=True,separators=(",",":")).encode()
def main():
 p=argparse.ArgumentParser();p.add_argument("--root",type=Path,required=True);p.add_argument("--descriptor",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args()
 root=a.root.resolve();desc=json.loads(a.descriptor.read_text());files={}
 for path in sorted(root.rglob("*")):
  if path.is_file() and path!=a.output and path.name!="authority.json":files[path.relative_to(root).as_posix()]=hashlib.sha256(path.read_bytes()).hexdigest()
 out={"schema":"factory-probe-authority/v1","version":desc["version"],"files":files,"classes":desc["classes"],"trusted_path":desc["trusted_path"],"analyzers":desc["analyzers"]}
 for aid,item in out["analyzers"].items():
  rel=item["argv"][0][2:];item["sha256"]=files[rel]
 for cname,entry in out["classes"].items():
  gate=entry["gate"];gate["probe_id"]=f"factory-root-probe:{cname}:gate:v1";gate["descriptor_sha256"]=hashlib.sha256(canonical({"argv":gate["argv"]})).hexdigest()
  for cap,item in entry["capabilities"].items():
   item["probe_id"]=f"factory-root-probe:{cname}:{cap}:v1";item["descriptor_sha256"]=hashlib.sha256(canonical({k:item[k] for k in ("argv","artifacts","semantic_id")})).hexdigest()
 raw=(json.dumps(out,sort_keys=True,indent=2)+"\n").encode();fd=os.open(a.output,os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_NOFOLLOW,0o600);os.write(fd,raw);os.fsync(fd);os.close(fd);print(hashlib.sha256(raw).hexdigest())
if __name__=="__main__":main()
