#!/usr/bin/env bash
# Source this script to refresh the project-local Ollama Cloud credentials.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
# Task 15 migration: the operator store lives OUTSIDE the model workspace —
# $OLLAMA_USAGE_ENV_FILE when set, otherwise $XDG_CONFIG_HOME/
# unattended-ralph/ollama-usage-env or ~/.config/unattended-ralph/
# ollama-usage-env.  The legacy workspace store is detected (metadata only)
# and never sourced as a credential authority.
if [[ -n "${OLLAMA_USAGE_ENV_FILE:-}" ]]; then
    ENV_FILE=${OLLAMA_USAGE_ENV_FILE}
elif [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
    ENV_FILE="$XDG_CONFIG_HOME/unattended-ralph/ollama-usage-env"
else
    ENV_FILE="${HOME:-}/.config/unattended-ralph/ollama-usage-env"
fi

if [[ -e "$PROJECT_ROOT/.ollama-usage-env" || -L "$PROJECT_ROOT/.ollama-usage-env" ]]; then
    echo "update-ollama-cookies: DEPRECATED legacy store $PROJECT_ROOT/.ollama-usage-env;" >&2
    echo "update-ollama-cookies: credentials now live in the operator store outside the workspace" >&2
    echo "update-ollama-cookies: (migrate it; the legacy store is never sourced as an authority)" >&2
fi

mkdir -p "$(dirname -- "$ENV_FILE")"
if [[ -r "$ENV_FILE" && -z ${OLLAMA_COOKIE:-} ]]; then
    # shellcheck source=/dev/null
    source "$ENV_FILE"
fi

prompt_secret() {
    local name=$1 label=$2 current input
    current=${!name:-}
    read -r -p "$label [${current:+set, hidden}]: " input
    [[ -z "$input" ]] || printf -v "$name" '%s' "$input"
    export "${name?}"
}

prompt_value() {
    local name=$1 label=$2 default=$3 current input
    current=${!name:-$default}
    read -r -p "$label [$current]: " input
    printf -v "$name" '%s' "${input:-$current}"
    export "${name?}"
}

echo "Updating Ollama usage guard parameters. Press Enter to keep a value."
prompt_secret __Secure_session "__Secure-session"
prompt_secret aid "aid"
prompt_secret cf_clearance "cf_clearance"
prompt_value OLLAMA_THRESHOLD "Usage threshold %" 80
prompt_value OLLAMA_WAIT_INTERVAL_SECONDS "Wait polling interval seconds" 300
prompt_value OLLAMA_WAIT_MAX_SECONDS "Maximum automatic wait seconds (0 = unlimited)" 0

if [[ -z ${__Secure_session:-} || -z ${aid:-} || -z ${cf_clearance:-} ]]; then
    echo "update-ollama-cookies: all three cookie values are required" >&2
    if [[ ${BASH_SOURCE[0]} != "$0" ]]; then
        return 2
    fi
    exit 2
fi

OLLAMA_COOKIE="__Secure-session=${__Secure_session}; aid=${aid}; cf_clearance=${cf_clearance}"
export OLLAMA_COOKIE

{
    echo "# Generated by scripts/update-ollama-cookies.sh"
    printf 'export __Secure_session=%q\n' "$__Secure_session"
    printf 'export aid=%q\n' "$aid"
    printf 'export cf_clearance=%q\n' "$cf_clearance"
    printf 'export OLLAMA_THRESHOLD=%q\n' "$OLLAMA_THRESHOLD"
    printf 'export OLLAMA_WAIT_INTERVAL_SECONDS=%q\n' "$OLLAMA_WAIT_INTERVAL_SECONDS"
    printf 'export OLLAMA_WAIT_MAX_SECONDS=%q\n' "$OLLAMA_WAIT_MAX_SECONDS"
    printf 'export OLLAMA_COOKIE=%q\n' "$OLLAMA_COOKIE"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "Saved owner-only credentials to $ENV_FILE"
echo "Test with: ./scripts/ollama-usage-guard.sh --check"
