"""Hidden `.factory/loop/` control-plane package (factory-plan/v1 and later)."""

from .gitutil import (
    GIT_ENV_STRIP,
    GIT_EXECUTABLE,
    GitBoundaryError,
    git_bytes,
    git_bytes_bounded,
    git_run,
    load_sibling,
    resolve_git_executable,
    sanitize_git_environment,
)
from .lock import (
    ENV_KEYS as LOCK_ENV_KEYS,
    CapturedProcess,
    EscapedDescendantError,
    PlanBinding,
    RootLock,
    RootLockBindingError,
    RootLockCommandError,
    RootLockError,
    RootLockHeldError,
    RootLockTimeoutError,
    RootLockUnsafeError,
    SpecBinding,
    acquire_root_lock,
    assert_no_escaped_descendants,
    capture_descendants,
    detect_escaped_descendants,
    live_scope,
    lock_environment,
    probe_root_lock,
    require_linux_primitives,
    stripped_child_env,
)
from .launch import (  # fresh-context execution and supervision (Task 6)
    DEFAULT_ALLOWED_TOOLS,
    DEFAULT_INACTIVITY_LIMIT,
    DEFAULT_RUNTIME_LIMIT,
    ENV_ALLOWLIST,
    INVOCATION_ENV_PREFIX,
    InvocationBinding,
    InvocationError,
    LaunchAuthority,
    LaunchError,
    LaunchResult,
    LaunchSupervision,
    OUTPUT_DIGEST_CAP,
    OUTPUT_TAIL_CAP,
    PROMPT_INPUT_MAX,
    PROMPT_MAX_BYTES,
    RESULT_SCHEMA_FILE,
    RESULT_SCHEMA_NAME,
    ROLES,
    SECURE_WRAPPER,
    StreamResult,
    SupervisionError,
    SupervisionSignalInterrupt,
    TASK_HEADING_RE,
    TERMINATION_SIGNALS,
    SUPPORTED_PROVIDERS,
    authorize_launch,
    child_argv,
    child_environment,
    compose_prompt,
    derive_task_excerpt,
    require_trusted_interpreter,
    secure_wrapper_path,
    task_excerpt_bytes,
    task_excerpt_digest,
    validate_launch_result,
    verify_child_env,
    verify_invocation,
    verify_task_excerpt,
)
from .plan_parser import (
    ALLOWED_TRANSITIONS,
    CLASSIFICATIONS,
    FINAL_AUDIT_TITLE,
    LIFECYCLE_STATUSES,
    MATRIX_HEADER,
    Plan,
    PlanError,
    SCHEMA_NAME,
    TASK_STATUSES,
    is_allowed_transition,
    parse_plan,
    round_trip,
)
from .workspace_confinement import (  # real Landlock authority (Task 8)
    ConfinementError as WorkspaceConfinementError,
    ConfinementProof as WorkspaceConfinementProof,
    ConfinementUnavailable as WorkspaceConfinementUnavailable,
    confinement_primitive_available,
    confinement_spec,
    prove_confinement as prove_workspace_confinement,
    validate_confinement_spec,
    validate_proof as validate_workspace_confinement_proof,
)
from .promptset import (
    PromptSetError,
    load_all_prompts,
    prompt_set_digest,
    read_role_prompt,
    role_prompt_digest,
)
from .audit_objectives import (
    AuditObjectiveError,
    load_registry as load_audit_objectives,
    registry_digest as audit_objective_registry_digest,
    select_audit_objective,
)
from .selector import (
    CLASSIFICATIONS as SELECTOR_CLASSIFICATIONS,
    Selection,
    SelectorError,
    select_task,
)
from .migration import (  # Ralph-free metadata-only migration authority
    DirtyEntry,
    EvidenceEntry,
    LegacyEnvStore,
    LegacySurface,
    MigrationError,
    MigrationSnapshot,
    MigrationSnapshotError,
    MigrationUnavailableError,
    derive_migration_snapshot,
    detect_legacy_env_store,
    is_ralph_frozen,
    legacy_surface,
    migrate_control_state,
    write_migration_report,
)
from .footprint import (  # hidden harness inventory authority (Task 13)
    FootprintError,
    FootprintReport,
    check_pinned_external_executables,
    classify_path as classify_footprint_path,
    inventory as inventory_footprint,
    product_discovery,
    remove_harness,
    verify_external_install,
    verify_product_install,
)
from .evidence import (  # immutable verifier/receipt authority (Task 12)
    EvidenceError,
    HeldVerifier,
    ReceiptError,
    TierError,
    VerifierBinding,
    VerifierBindingError,
    bind_verifier,
    evidence_tier_ceiling,
    parse_evidence_lines,
    revalidate_verifier,
    validate_evidence_lines,
    validate_evidence_text,
    validate_manifest_ref,
    validate_receipt,
)
from .redaction import (  # exact-commit credential output authority (Task 11)
    OutputRedactionError,
    Redactor,
    read_worktree_guard_source,
    redact_text,
    redactor_for,
    redactor_from_bytes,
    scan_key_block_state,
)
from .findings import (  # receipt-backed next-planner findings authority (Task 10)
    FindingsError,
    FindingsForeignError,
    FindingsMalformedError,
    FindingsReceiptError,
    FindingsStaleError,
    FindingsSyntheticError,
    build_payload as build_findings_payload,
    build_receipt as build_findings_receipt,
    consume_next_round_findings,
    payload_bytes as findings_payload_bytes,
    publish_receipt as publish_findings_receipt,
    read_receipt as read_findings_receipt,
    validate_payload as validate_findings_payload,
    validate_receipt as validate_findings_receipt,
)
from .verifier_failure import (  # strict structured verifier-failure artifact (EVID-02)
    CAPABILITY_CLASSIFICATIONS,
    ENVIRONMENT_CLASSIFICATIONS,
    MAX_ARTIFACT_BYTES,
    PHASES as VERIFIER_FAILURE_PHASES,
    RERUN_SCOPES,
    SCHEMA_NAME as VERIFIER_FAILURE_SCHEMA_NAME,
    VerifierFailureError,
    VerifierFailureMalformedError,
    artifact_bytes as verifier_failure_bytes,
    build_artifact as build_verifier_failure,
    parse_artifact as parse_verifier_failure,
    validate_artifact as validate_verifier_failure,
    validate_commit_context as validate_verifier_failure_commit,
)
from .task_budget import (  # versioned strict task-resource budget (Phase 2A)
    BUDGET_CONFIG_FILE,
    DEFAULT_TASK_BUDGET,
    EXHAUSTION_REASONS,
    LEDGER_SCHEMA_NAME,
    MAX_BUDGET_BYTES,
    MAX_CPU_TIME_SECONDS,
    MAX_LEDGER_BYTES,
    MAX_LIVE_PROCESSES,
    MAX_OUTPUT_BYTES,
    MAX_PER_COMMAND_TIMEOUT_SECONDS,
    MAX_WALL_TIME_SECONDS,
    SCHEMA_NAME as TASK_BUDGET_SCHEMA_NAME,
    BudgetLedger,
    TaskBudgetError,
    TaskBudgetMalformedError,
    budget_bytes as task_budget_bytes,
    exhausted_reason as task_budget_exhausted_reason,
    ledger_bytes as task_budget_ledger_bytes,
    load_budget_config as load_task_budget_config,
    load_ledger as load_task_budget_ledger,
    parse_budget as parse_task_budget,
    parse_ledger as parse_task_budget_ledger,
    remaining_limits as task_budget_remaining_limits,
    save_ledger as save_task_budget_ledger,
    validate_budget as validate_task_budget,
)
from .scheduler import (  # adaptive campaign/audit scheduler authority (Phase 2B2)
    AUDIT_OUTCOMES,
    BUDGET_RELPATH as CAMPAIGN_BUDGET_RELPATH,
    DEFAULT_AUDIT_INTERVAL,
    DEFAULT_MAX_CHECKPOINTS,
    DEFAULT_MAX_ROUNDS,
    DEFAULT_MAX_TASK_ATTEMPTS,
    DEFAULT_MAX_WALL_SECONDS,
    DEFAULT_NO_PROGRESS_LIMIT,
    MAX_AUDIT_INTERVAL_CAP,
    MAX_BUDGET_BYTES as CAMPAIGN_BUDGET_MAX_BYTES,
    MAX_CHECKPOINTS_CAP,
    MAX_NO_PROGRESS_LIMIT_CAP,
    MAX_OBJECTIVES as CAMPAIGN_BUDGET_MAX_OBJECTIVES,
    MAX_PATH_LENGTH as CAMPAIGN_BUDGET_MAX_PATH_LENGTH,
    MAX_ROUNDS_CAP,
    MAX_SECURITY_PATHS as CAMPAIGN_BUDGET_MAX_SECURITY_PATHS,
    MAX_TASK_ATTEMPTS_CAP,
    MAX_WALL_SECONDS_CAP,
    SCHEMA_FILE as CAMPAIGN_BUDGET_SCHEMA_FILE,
    SCHEMA_NAME as CAMPAIGN_BUDGET_SCHEMA_NAME,
    TERMINAL_REASONS,
    CampaignBudget,
    SchedulerConfigError,
    SchedulerError,
    audit_next_phase,
    default_budget as default_campaign_budget,
    is_security_sensitive,
    load_budget_config as load_campaign_budget,
    objective_coverage,
    parse_budget as parse_campaign_budget,
    progress_fingerprint,
    security_sensitive_changed,
    should_audit,
)
from .path_lease import (  # Phase 2C1 task-scoped path-lease authority (LEASE-01)
    CLAIM_SCHEMA_FILE as PATH_LEASE_CLAIM_SCHEMA_FILE,
    CLAIM_SCHEMA_NAME as PATH_LEASE_CLAIM_SCHEMA_NAME,
    DEFAULT_LEASE_SECONDS,
    MAX_LEASE_SECONDS,
    POLICY_RELPATH as PATH_LEASE_POLICY_RELPATH,
    POLICY_SCHEMA_FILE as PATH_LEASE_POLICY_SCHEMA_FILE,
    SCHEMA_NAME as PATH_LEASE_POLICY_SCHEMA_NAME,
    LeaseScope,
    PathLeaseClaimError,
    PathLeaseContextError,
    PathLeaseError,
    PathLeasePolicy,
    PathLeasePolicyError,
    TaskPathLease,
    canonical_claim_bytes as path_lease_canonical_claim_bytes,
    canonical_policy_bytes as path_lease_canonical_policy_bytes,
    claim_digest as path_lease_claim_digest,
    claim_to_bytes as path_lease_claim_to_bytes,
    expand_request as path_lease_expand_request,
    is_safe_path as path_lease_is_safe_path,
    is_safe_pattern as path_lease_is_safe_pattern,
    is_scope_id as path_lease_is_scope_id,
    load_policy_config as load_path_lease_policy,
    mint_claim as mint_path_lease_claim,
    parse_claim as parse_path_lease_claim,
    parse_policy as parse_path_lease_policy,
    policy_digest as path_lease_policy_digest,
    validate_claim as validate_path_lease_claim,
    validate_claim_context as validate_path_lease_claim_context,
)
from .state import (  # factory-state/v1 control-state authority (STATE-01)
    AUDIT_FINAL_TARGETS,
    BINDING_FIELDS,
    DIGEST_LEDGER_NAME,
    FIELD_NAMES,
    LEDGER_MAX,
    OUTCOMES,
    PHASES,
    PHASE_OUTCOMES,
    PHASE_VALUES,
    RETRY_OUTCOMES,
    SCHEMA_NAME,
    STATE_FILE_MAX,
    STATE_FILE_NAME,
    TERMINAL_PHASES,
    TRANSITIONS,
    FactoryState,
    StateBindingError,
    StateDigestError,
    StateError,
    StateIOError,
    StateTamperError,
    StateTransitionError,
    advance,
    begin_attempt,
    init_state,
    live_branch,
    load_state,
    owner_tamper_gate,
    parse_state,
    record_phase_digest,
    record_retry,
    recover_state,
    read_phase_digest_ledger,
    repository_identity,
    state_digest,
    verify_phase_digest,
    write_state,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AUDIT_FINAL_TARGETS",
    "AUDIT_OUTCOMES",
    "AuditObjectiveError",
    "BINDING_FIELDS",
    "CapturedProcess",
    "CLASSIFICATIONS",
    "DEFAULT_ALLOWED_TOOLS",
    "DEFAULT_AUDIT_INTERVAL",
    "DEFAULT_INACTIVITY_LIMIT",
    "DEFAULT_MAX_CHECKPOINTS",
    "DEFAULT_MAX_ROUNDS",
    "DEFAULT_MAX_TASK_ATTEMPTS",
    "DEFAULT_MAX_WALL_SECONDS",
    "DEFAULT_NO_PROGRESS_LIMIT",
    "DEFAULT_RUNTIME_LIMIT",
    "DIGEST_LEDGER_NAME",
    "ENV_ALLOWLIST",
    "FORBIDDEN_OLD_PROMPTS",
    "FORBIDDEN_TRACKED_EXACT",
    "FORBIDDEN_TRACKED_GLOBS",
    "FORBIDDEN_TRACKED_PREFIXES",
    "FREEZE_MARKER_RELPATH",
    "BudgetLedger",
    "CAMPAIGN_BUDGET_MAX_BYTES",
    "CAMPAIGN_BUDGET_MAX_OBJECTIVES",
    "CAMPAIGN_BUDGET_MAX_PATH_LENGTH",
    "CAMPAIGN_BUDGET_MAX_SECURITY_PATHS",
    "CAMPAIGN_BUDGET_RELPATH",
    "CAMPAIGN_BUDGET_SCHEMA_FILE",
    "CAMPAIGN_BUDGET_SCHEMA_NAME",
    "CampaignBudget",
    "EXHAUSTION_REASONS",
    "EvidenceError",
    "EscapedDescendantError",
    "FIELD_NAMES",
    "FINAL_AUDIT_TITLE",
    "FactoryState",
    "FootprintError",
    "FootprintReport",
    "FindingsError",
    "FindingsForeignError",
    "FindingsMalformedError",
    "FindingsReceiptError",
    "FindingsStaleError",
    "FindingsSyntheticError",
    "GIT_ENV_STRIP",
    "GIT_EXECUTABLE",
    "GitBoundaryError",
    "HeldVerifier",
    "INVOCATION_ENV_PREFIX",
    "InvocationBinding",
    "InvocationError",
    "LEDGER_MAX",
    "LEDGER_SCHEMA_NAME",
    "LIFECYCLE_STATUSES",
    "LOCK_ENV_KEYS",
    "LaunchAuthority",
    "LaunchError",
    "LaunchResult",
    "LaunchSupervision",
    "MAX_AUDIT_INTERVAL_CAP",
    "MAX_BUDGET_BYTES",
    "MAX_CHECKPOINTS_CAP",
    "MAX_CPU_TIME_SECONDS",
    "MAX_LEDGER_BYTES",
    "MAX_LIVE_PROCESSES",
    "MAX_NO_PROGRESS_LIMIT_CAP",
    "MAX_OUTPUT_BYTES",
    "MAX_PER_COMMAND_TIMEOUT_SECONDS",
    "MAX_ROUNDS_CAP",
    "MAX_TASK_ATTEMPTS_CAP",
    "MAX_WALL_SECONDS_CAP",
    "MAX_WALL_TIME_SECONDS",
    "MATRIX_HEADER",
    "MIGRATION_SCHEMA",
    "MAX_LEASE_SECONDS",
    "MigrationError",
    "MigrationUnavailableError",
    "OUTCOMES",
    "OUTPUT_DIGEST_CAP",
    "OUTPUT_TAIL_CAP",
    "OutputRedactionError",
    "PHASES",
    "PHASE_OUTCOMES",
    "PHASE_VALUES",
    "PATH_LEASE_CLAIM_SCHEMA_FILE",
    "PATH_LEASE_CLAIM_SCHEMA_NAME",
    "PATH_LEASE_POLICY_RELPATH",
    "PATH_LEASE_POLICY_SCHEMA_FILE",
    "PATH_LEASE_POLICY_SCHEMA_NAME",
    "PathLeaseClaimError",
    "PathLeaseContextError",
    "PathLeaseError",
    "PathLeasePolicy",
    "PathLeasePolicyError",
    "PROMPT_INPUT_MAX",
    "PROMPT_MAX_BYTES",
    "PromptSetError",
    "Plan",
    "PlanBinding",
    "PlanError",
    "RESULT_SCHEMA_FILE",
    "RESULT_SCHEMA_NAME",
    "RETRY_OUTCOMES",
    "ReceiptError",
    "ROLES",
    "Redactor",
    "RootLock",
    "RootLockBindingError",
    "RootLockCommandError",
    "RootLockError",
    "RootLockHeldError",
    "RootLockTimeoutError",
    "RootLockUnsafeError",
    "SCHEMA_NAME",
    "SchedulerConfigError",
    "SchedulerError",
    "SECURE_WRAPPER",
    "SELECTOR_CLASSIFICATIONS",
    "Selection",
    "SelectorError",
    "SpecBinding",
    "STATE_FILE_MAX",
    "STATE_FILE_NAME",
    "StreamResult",
    "SupervisionError",
    "SupervisionSignalInterrupt",
    "TASK_BUDGET_SCHEMA_NAME",
    "TASK_HEADING_RE",
    "TaskBudgetError",
    "TaskBudgetMalformedError",
    "TaskPathLease",
    "TERMINAL_REASONS",
    "TERMINATION_SIGNALS",
    "TERMINAL_PHASES",
    "TRANSITIONS",
    "TierError",
    "TASK_STATUSES",
    "SUPPORTED_PROVIDERS",
    "StateBindingError",
    "StateDigestError",
    "StateError",
    "StateIOError",
    "StateTamperError",
    "StateTransitionError",
    "VerifierBinding",
    "VerifierBindingError",
    "VerifierFailureError",
    "VerifierFailureMalformedError",
    "VERIFIER_FAILURE_PHASES",
    "VERIFIER_FAILURE_SCHEMA_NAME",
    "WorkspaceConfinementError",
    "WorkspaceConfinementProof",
    "WorkspaceConfinementUnavailable",
    "acquire_root_lock",
    "advance",
    "assert_no_escaped_descendants",
    "audit_next_phase",
    "authorize_launch",
    "begin_attempt",
    "bind_verifier",
    "build_findings_payload",
    "build_findings_receipt",
    "build_verifier_failure",
    "budget_bytes",
    "capture_descendants",
    "check_pinned_external_executables",
    "classify_footprint_path",
    "audit_objective_registry_digest",
    "child_argv",
    "child_environment",
    "compose_prompt",
    "confinement_primitive_available",
    "confinement_spec",
    "default_campaign_budget",
    "derive_task_excerpt",
    "detect_escaped_descendants",
    "consume_next_round_findings",
    "evidence_tier_ceiling",
    "findings_payload_bytes",
    "git_bytes",
    "git_bytes_bounded",
    "git_run",
    "init_state",
    "inventory_footprint",
    "is_security_sensitive",
    "is_allowed_transition",
    "forbidden_tracked",
    "freeze_marker_status",
    "is_ralph_frozen",
    "live_branch",
    "live_scope",
    "load_campaign_budget",
    "load_all_prompts",
    "load_audit_objectives",
    "load_path_lease_policy",
    "load_sibling",
    "load_state",
    "load_task_budget_config",
    "load_task_budget_ledger",
    "lock_environment",
    "mint_path_lease_claim",
    "objective_coverage",
    "owner_tamper_gate",
    "parse_campaign_budget",
    "parse_evidence_lines",
    "parse_path_lease_claim",
    "parse_path_lease_policy",
    "parse_plan",
    "parse_state",
    "parse_task_budget",
    "parse_task_budget_ledger",
    "path_lease_canonical_claim_bytes",
    "path_lease_canonical_policy_bytes",
    "path_lease_claim_digest",
    "path_lease_claim_to_bytes",
    "path_lease_expand_request",
    "path_lease_is_safe_path",
    "path_lease_is_safe_pattern",
    "path_lease_is_scope_id",
    "path_lease_policy_digest",
    "progress_fingerprint",
    "probe_root_lock",
    "product_discovery",
    "publish_findings_receipt",
    "prove_workspace_confinement",
    "prompt_set_digest",
    "read_findings_receipt",
    "read_role_prompt",
    "ralph_presence",
    "read_worktree_guard_source",
    "record_phase_digest",
    "record_retry",
    "recover_state",
    "read_phase_digest_ledger",
    "redact_text",
    "redactor_for",
    "redactor_from_bytes",
    "remove_harness",
    "revalidate_verifier",
    "repository_identity",
    "role_prompt_digest",
    "require_linux_primitives",
    "require_trusted_interpreter",
    "resolve_git_executable",
    "round_trip",
    "sanitize_git_environment",
    "scan_key_block_state",
    "secure_wrapper_path",
    "save_task_budget_ledger",
    "security_sensitive_changed",
    "select_audit_objective",
    "select_task",
    "should_audit",
    "state_digest",
    "stripped_child_env",
    "task_budget_bytes",
    "task_budget_exhausted_reason",
    "task_budget_ledger_bytes",
    "task_budget_remaining_limits",
    "task_excerpt_bytes",
    "task_excerpt_digest",
    "validate_confinement_spec",
    "validate_evidence_lines",
    "validate_evidence_text",
    "validate_findings_payload",
    "validate_findings_receipt",
    "validate_path_lease_claim",
    "validate_path_lease_claim_context",
    "validate_verifier_failure",
    "validate_verifier_failure_commit",
    "validate_launch_result",
    "validate_manifest_ref",
    "validate_receipt",
    "validate_workspace_confinement_proof",
    "verify_child_env",
    "verify_external_install",
    "verify_invocation",
    "verify_migration",
    "verify_product_install",
    "verify_phase_digest",
    "verify_task_excerpt",
    "verifier_failure_bytes",
    "write_state",
]
